//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_ContactList
    {
        public long ID { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> FriendId { get; set; }
        public string UserType { get; set; }
        public string FriendType { get; set; }
        public Nullable<bool> IsConnected { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
