//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseBlockUserList
    {
        public long ID { get; set; }
        public Nullable<long> CourseAdminId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> BlockedUserId { get; set; }
        public Nullable<bool> IsBlockedGolfer { get; set; }
    }
}
