//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_COUNTY
    {
        public int ID { get; set; }
        public string COUNTY_NAME { get; set; }
        public string COUNTY_CODE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
