//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseBuilder
    {
        public GF_CourseBuilder()
        {
            this.GF_CourseBuilderHolesDetail = new HashSet<GF_CourseBuilderHolesDetail>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<long> CourseID { get; set; }
        public string CoordinateType { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string BuildBy { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
    
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
        public virtual ICollection<GF_CourseBuilderHolesDetail> GF_CourseBuilderHolesDetail { get; set; }
    }
}
