//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_GolferWallet
    {
        public long Wlt_ID { get; set; }
        public string CCName { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public string CCNumber { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Golfer_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string MembershipID { get; set; }
        public string StatusText { get; set; }
    
        public virtual GF_Golfer GF_Golfer { get; set; }
    }
}
