//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_MassMessages
    {
        public long MassMsgId { get; set; }
        public string MessageTitle { get; set; }
        public string Message { get; set; }
        public Nullable<long> SendToUserID { get; set; }
        public string SendToUserName { get; set; }
        public string SendToUserEmail { get; set; }
        public string SendToCourseName { get; set; }
        public Nullable<long> SendToCourseId { get; set; }
        public string EmailStatus { get; set; }
        public string EmailStatusReason { get; set; }
        public string SendToUserType { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Status { get; set; }
        public string MessageBy { get; set; }
        public Nullable<long> CourseId { get; set; }
    }
}
