//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Modules
    {
        public GF_Modules()
        {
            this.GF_RoleModules = new HashSet<GF_RoleModules>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsFrontEnd { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> GroupId { get; set; }
    
        public virtual ICollection<GF_RoleModules> GF_RoleModules { get; set; }
    }
}
