//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_SMTPSettings
    {
        public long ID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public string SMTPHost { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPUserName { get; set; }
        public string FromEmail { get; set; }
        public string SMTPPort { get; set; }
        public string AdminEmail { get; set; }
        public string ReplyEmail { get; set; }
        public Nullable<bool> EnableSsl { get; set; }
        public Nullable<bool> EnableTls { get; set; }
    }
}
