//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Templates
    {
        public long ID { get; set; }
        public string TemplateName { get; set; }
        public string DefaultHTMLPath { get; set; }
        public string DefaultCSSPath { get; set; }
        public string DefaultLogoPath { get; set; }
    }
}
