//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_UserCurrentPosition
    {
        public long ID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public string ReferenceType { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
    }
}
