//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_AdminUsers
    {
        public GF_AdminUsers()
        {
            this.GF_CourseUsers = new HashSet<GF_CourseUsers>();
        }
    
        public long ID { get; set; }
        public Nullable<long> RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public string SALT { get; set; }
        public Nullable<long> CourseId { get; set; }
        public string DeviceType { get; set; }
        public string APNID { get; set; }
        public string GCMID { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string Image { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public Nullable<System.DateTime> LastLoginAttempt { get; set; }
        public Nullable<int> AppVersion { get; set; }
        public string DeviceSerialNo { get; set; }
        public Nullable<bool> ReceiveResolutionMails { get; set; }
    
        public virtual ICollection<GF_CourseUsers> GF_CourseUsers { get; set; }
    }
}
