//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseMenu
    {
        public GF_CourseMenu()
        {
            this.GF_CourseFoodItem = new HashSet<GF_CourseFoodItem>();
        }
    
        public long ID { get; set; }
        public long CourseID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
    
        public virtual GF_Category GF_Category { get; set; }
        public virtual ICollection<GF_CourseFoodItem> GF_CourseFoodItem { get; set; }
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
    }
}
