//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseFoodItem
    {
        public GF_CourseFoodItem()
        {
            this.GF_CourseFoodItemDetail = new HashSet<GF_CourseFoodItemDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public string AllowStatus { get; set; }
        public Nullable<bool> IsAllow { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<long> CourseMenuID { get; set; }
    
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
        public virtual GF_SubCategory GF_SubCategory { get; set; }
        public virtual ICollection<GF_CourseFoodItemDetail> GF_CourseFoodItemDetail { get; set; }
        public virtual GF_CourseMenu GF_CourseMenu { get; set; }
    }
}
