//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseInfo
    {
        public GF_CourseInfo()
        {
            this.GF_CourseUsers = new HashSet<GF_CourseUsers>();
            this.GF_GolferUser = new HashSet<GF_GolferUser>();
            this.GF_PromoCode = new HashSet<GF_PromoCode>();
            this.GF_ResolutionCenter = new HashSet<GF_ResolutionCenter>();
            this.GF_UserCurrentPosition = new HashSet<GF_UserCurrentPosition>();
            this.GF_CourseFoodItem = new HashSet<GF_CourseFoodItem>();
            this.GF_FoodCommission = new HashSet<GF_FoodCommission>();
            this.GF_CourseMenu = new HashSet<GF_CourseMenu>();
            this.GF_CourseVisitLog = new HashSet<GF_CourseVisitLog>();
            this.GF_CourseBuilder = new HashSet<GF_CourseBuilder>();
            this.GF_Order = new HashSet<GF_Order>();
            this.GF_GamePlayRound = new HashSet<GF_GamePlayRound>();
            this.GF_CourseFoodItemOption = new HashSet<GF_CourseFoodItemOption>();
        }
    
        public long ID { get; set; }
        public string CAT { get; set; }
        public string COURSE_NAME { get; set; }
        public string TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string YEARBUILT { get; set; }
        public string GREENGRASSTYPE { get; set; }
        public string FAIRWAYSGRASSTYPE { get; set; }
        public string WATERHAZARDS { get; set; }
        public string SANDBUNKERS { get; set; }
        public string NUMBEROFHOLES { get; set; }
        public string YARDAGEMARKERS { get; set; }
        public string ACCEPTTEATIMES { get; set; }
        public string EARLIESCALLTEATIME { get; set; }
        public string TRAININGFACILITIES { get; set; }
        public string ONSITE_GOLFPRO { get; set; }
        public string SPIKES { get; set; }
        public string GUESTS { get; set; }
        public string ACCESS { get; set; }
        public string DISCOUNTS { get; set; }
        public string RENTALCLUBS { get; set; }
        public string PULLCARTS { get; set; }
        public string WALKING { get; set; }
        public string RESTAURANT { get; set; }
        public string BAR { get; set; }
        public string HOURS { get; set; }
        public string Food { get; set; }
        public string AVAILABLEPRODUCTS { get; set; }
        public string HOMESONCOURSE { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PlateformFee { get; set; }
        public string PartnershipStatus { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPlateformFeeActive { get; set; }
        public Nullable<int> Par { get; set; }
        public Nullable<int> Par_1 { get; set; }
        public Nullable<int> Hole_1 { get; set; }
        public Nullable<int> Hdcp_1 { get; set; }
        public Nullable<int> Par_2 { get; set; }
        public Nullable<int> Hole_2 { get; set; }
        public Nullable<int> Hdcp_2 { get; set; }
        public Nullable<int> Par_3 { get; set; }
        public Nullable<int> Hole_3 { get; set; }
        public Nullable<int> Hdcp_3 { get; set; }
        public Nullable<int> Par_4 { get; set; }
        public Nullable<int> Hole_4 { get; set; }
        public Nullable<int> Hdcp_4 { get; set; }
        public Nullable<int> Par_5 { get; set; }
        public Nullable<int> Hole_5 { get; set; }
        public Nullable<int> Hdcp_5 { get; set; }
        public Nullable<int> Par_6 { get; set; }
        public Nullable<int> Hole_6 { get; set; }
        public Nullable<int> Hdcp_6 { get; set; }
        public Nullable<int> Par_7 { get; set; }
        public Nullable<int> Hole_7 { get; set; }
        public Nullable<int> Hdcp_7 { get; set; }
        public Nullable<int> Par_8 { get; set; }
        public Nullable<int> Hole_8 { get; set; }
        public Nullable<int> Hdcp_8 { get; set; }
        public Nullable<int> Par_9 { get; set; }
        public Nullable<int> Hole_9 { get; set; }
        public Nullable<int> Hdcp_9 { get; set; }
        public Nullable<int> Par_10 { get; set; }
        public Nullable<int> Hole_10 { get; set; }
        public Nullable<int> Hdcp_10 { get; set; }
        public Nullable<int> Par_11 { get; set; }
        public Nullable<int> Hole_11 { get; set; }
        public Nullable<int> Hdcp_11 { get; set; }
        public Nullable<int> Par_12 { get; set; }
        public Nullable<int> Hole_12 { get; set; }
        public Nullable<int> Hdcp_12 { get; set; }
        public Nullable<int> Par_13 { get; set; }
        public Nullable<int> Hole_13 { get; set; }
        public Nullable<int> Hdcp_13 { get; set; }
        public Nullable<int> Par_14 { get; set; }
        public Nullable<int> Hole_14 { get; set; }
        public Nullable<int> Hdcp_14 { get; set; }
        public Nullable<int> Par_15 { get; set; }
        public Nullable<int> Hole_15 { get; set; }
        public Nullable<int> Hdcp_15 { get; set; }
        public Nullable<int> Par_16 { get; set; }
        public Nullable<int> Hole_16 { get; set; }
        public Nullable<int> Hdcp_16 { get; set; }
        public Nullable<int> Par_17 { get; set; }
        public Nullable<int> Hole_17 { get; set; }
        public Nullable<int> Hdcp_17 { get; set; }
        public Nullable<int> Par_18 { get; set; }
        public Nullable<int> Hole_18 { get; set; }
        public Nullable<int> Hole_1_Red { get; set; }
        public Nullable<int> Hole_1_Blue { get; set; }
        public Nullable<int> Hole_2_Red { get; set; }
        public Nullable<int> Hole_2_Blue { get; set; }
        public Nullable<int> Hole_3_Red { get; set; }
        public Nullable<int> Hole_3_Blue { get; set; }
        public Nullable<int> Hole_4_Red { get; set; }
        public Nullable<int> Hole_4_Blue { get; set; }
        public Nullable<int> Hole_5_Red { get; set; }
        public Nullable<int> Hole_5_Blue { get; set; }
        public Nullable<int> Hole_6_Red { get; set; }
        public Nullable<int> Hole_6_Blue { get; set; }
        public Nullable<int> Hole_7_Red { get; set; }
        public Nullable<int> Hole_7_Blue { get; set; }
        public Nullable<int> Hole_8_Red { get; set; }
        public Nullable<int> Hole_8_Blue { get; set; }
        public Nullable<int> Hole_9_Red { get; set; }
        public Nullable<int> Hole_9_Blue { get; set; }
        public Nullable<int> Hole_10_Red { get; set; }
        public Nullable<int> Hole_10_Blue { get; set; }
        public Nullable<int> Hole_11_Red { get; set; }
        public Nullable<int> Hole_11_Blue { get; set; }
        public Nullable<int> Hole_12_Red { get; set; }
        public Nullable<int> Hole_12_Blue { get; set; }
        public Nullable<int> Hole_13_Red { get; set; }
        public Nullable<int> Hole_13_Blue { get; set; }
        public Nullable<int> Hole_14_Red { get; set; }
        public Nullable<int> Hole_14_Blue { get; set; }
        public Nullable<int> Hole_15_Red { get; set; }
        public Nullable<int> Hole_15_Blue { get; set; }
        public Nullable<int> Hole_16_Red { get; set; }
        public Nullable<int> Hole_16_Blue { get; set; }
        public Nullable<int> Hole_17_Red { get; set; }
        public Nullable<int> Hole_17_Blue { get; set; }
        public Nullable<int> Hole_18_Red { get; set; }
        public Nullable<int> Hole_18_Blue { get; set; }
        public string Country { get; set; }
        public Nullable<int> Hdcp_18 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<bool> IsClubHouse { get; set; }
        public Nullable<long> ClubHouseID { get; set; }
    
        public virtual ICollection<GF_CourseUsers> GF_CourseUsers { get; set; }
        public virtual ICollection<GF_GolferUser> GF_GolferUser { get; set; }
        public virtual ICollection<GF_PromoCode> GF_PromoCode { get; set; }
        public virtual ICollection<GF_ResolutionCenter> GF_ResolutionCenter { get; set; }
        public virtual ICollection<GF_UserCurrentPosition> GF_UserCurrentPosition { get; set; }
        public virtual ICollection<GF_CourseFoodItem> GF_CourseFoodItem { get; set; }
        public virtual ICollection<GF_FoodCommission> GF_FoodCommission { get; set; }
        public virtual ICollection<GF_CourseMenu> GF_CourseMenu { get; set; }
        public virtual ICollection<GF_CourseVisitLog> GF_CourseVisitLog { get; set; }
        public virtual ICollection<GF_CourseBuilder> GF_CourseBuilder { get; set; }
        public virtual ICollection<GF_Order> GF_Order { get; set; }
        public virtual ICollection<GF_GamePlayRound> GF_GamePlayRound { get; set; }
        public virtual ICollection<GF_CourseFoodItemOption> GF_CourseFoodItemOption { get; set; }
    }
}
