//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_EmailTemplatesFields
    {
        public long ID { get; set; }
        public Nullable<long> EmailTemplateId { get; set; }
        public string FieldName { get; set; }
        public string FieldDescription { get; set; }
    }
}
