//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_GolferPaceofPlay_Temp
    {
        public long id { get; set; }
        public Nullable<long> GolferId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> HoleNumber { get; set; }
        public string Position { get; set; }
        public string Status { get; set; }
        public Nullable<long> GameRoundID { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string Type { get; set; }
    }
}
