//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_GamePlayScoreCard
    {
        public long ID { get; set; }
        public Nullable<long> RoundID { get; set; }
        public Nullable<int> HoleNo { get; set; }
        public Nullable<long> Distance { get; set; }
        public Nullable<int> Par { get; set; }
        public Nullable<int> PlayerOneScore { get; set; }
        public Nullable<int> PlayerTwoScore { get; set; }
        public Nullable<int> PlayerThreeScore { get; set; }
        public Nullable<int> PlayerFourScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual GF_GamePlayRound GF_GamePlayRound { get; set; }
    }
}
