//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Golfer
    {
        public GF_Golfer()
        {
            this.GF_CourseVisitLog = new HashSet<GF_CourseVisitLog>();
            this.GF_GamePlayRound = new HashSet<GF_GamePlayRound>();
            this.GF_GolferRating = new HashSet<GF_GolferRating>();
            this.GF_GolferUser = new HashSet<GF_GolferUser>();
            this.GF_GolferWallet = new HashSet<GF_GolferWallet>();
            this.GF_Order = new HashSet<GF_Order>();
            this.GF_ResolutionCenter = new HashSet<GF_ResolutionCenter>();
        }
    
        public long GF_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Status { get; set; }
        public string APNID { get; set; }
        public string DeviceType { get; set; }
        public string GCMID { get; set; }
        public string Salt { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<long> IncomeID { get; set; }
        public Nullable<bool> IsReceiveEmail { get; set; }
        public Nullable<bool> IsReceivePushNotification { get; set; }
        public string Race { get; set; }
        public Nullable<int> Tee { get; set; }
        public Nullable<bool> IsReceiveChatMessages { get; set; }
        public string strTimeZone { get; set; }
        public Nullable<long> TimeZoneId { get; set; }
        public string DeviceSerialNo { get; set; }
        public Nullable<int> AppVersion { get; set; }
        public Nullable<bool> IsReceiveEmailGolfer { get; set; }
        public Nullable<bool> IsReceivePushNotificationGolfer { get; set; }
        public string measurement { get; set; }
        public string temperature { get; set; }
        public string speed { get; set; }
    
        public virtual ICollection<GF_CourseVisitLog> GF_CourseVisitLog { get; set; }
        public virtual ICollection<GF_GamePlayRound> GF_GamePlayRound { get; set; }
        public virtual ICollection<GF_GolferRating> GF_GolferRating { get; set; }
        public virtual ICollection<GF_GolferUser> GF_GolferUser { get; set; }
        public virtual ICollection<GF_GolferWallet> GF_GolferWallet { get; set; }
        public virtual ICollection<GF_Order> GF_Order { get; set; }
        public virtual ICollection<GF_ResolutionCenter> GF_ResolutionCenter { get; set; }
    }
}
