//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_MenuItems
    {
        public GF_MenuItems()
        {
            this.GF_OrderDetails = new HashSet<GF_OrderDetails>();
            this.GF_CourseFoodItemDetail = new HashSet<GF_CourseFoodItemDetail>();
            this.GF_MenuItemOption = new HashSet<GF_MenuItemOption>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<decimal> Commission { get; set; }
    
        public virtual GF_SubCategory GF_SubCategory { get; set; }
        public virtual ICollection<GF_OrderDetails> GF_OrderDetails { get; set; }
        public virtual ICollection<GF_CourseFoodItemDetail> GF_CourseFoodItemDetail { get; set; }
        public virtual ICollection<GF_MenuItemOption> GF_MenuItemOption { get; set; }
    }
}
