//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Messages
    {
        public long ID { get; set; }
        public Nullable<long> MsgFrom { get; set; }
        public Nullable<long> MsgTo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Image { get; set; }
        public string ImagePath { get; set; }
        public string Type { get; set; }
        public string IsMessagesFromGolfer { get; set; }
        public string IsMessagesToGolfer { get; set; }
        public Nullable<long> CourseId { get; set; }
    }
}
