//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Order
    {
        public GF_Order()
        {
            this.GF_OrderDetails = new HashSet<GF_OrderDetails>();
        }
    
        public long ID { get; set; }
        public Nullable<long> GolferID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GolferPlatformFee { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> CartieId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<long> KitchenId { get; set; }
        public Nullable<long> ProShopID { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsPickup { get; set; }
        public string OrderType { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string Stripe_ChargeId { get; set; }
        public string Stripe_CustomerId { get; set; }
        public string HEXColor { get; set; }
        public string RGBColor { get; set; }
        public string HUEColor { get; set; }
        public Nullable<long> GolferWalletId { get; set; }
        public Nullable<bool> IsReadyByKitchen { get; set; }
        public Nullable<bool> IsReadyByProshop { get; set; }
        public string OrderStatus { get; set; }
        public string StripeToken { get; set; }
        public string MemberShipID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<long> PromoCodeID { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Stripe_Course_ChargeId { get; set; }
        public string StripeCourseToken { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<decimal> GPFRate { get; set; }
        public Nullable<decimal> CoursePlatformFee { get; set; }
        public Nullable<decimal> CPFRate { get; set; }
        public string BT_TransId { get; set; }
        public string CardNumber { get; set; }
        public string CardExpMonth { get; set; }
        public string CardExpYear { get; set; }
        public string CardCCV { get; set; }
        public string BT_ResponseText { get; set; }
        public Nullable<int> HoleNo { get; set; }
    
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
        public virtual GF_PromoCode GF_PromoCode { get; set; }
        public virtual ICollection<GF_OrderDetails> GF_OrderDetails { get; set; }
        public virtual GF_Golfer GF_Golfer { get; set; }
    }
}
