//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_OrderAcceptReject
    {
        public long ID { get; set; }
        public Nullable<long> CartieID { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual GF_Order GF_Order { get; set; }
    }
}
