//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolferWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GolflerEntities : DbContext
    {
        public GolflerEntities()
            : base("name=GolflerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GF_AdminUsers> GF_AdminUsers { get; set; }
        public DbSet<GF_Category> GF_Category { get; set; }
        public DbSet<GF_Courses> GF_Courses { get; set; }
        public DbSet<GF_CourseSuggest> GF_CourseSuggest { get; set; }
        public DbSet<GF_CourseUsers> GF_CourseUsers { get; set; }
        public DbSet<GF_SubCategory> GF_SubCategory { get; set; }
        public DbSet<GF_Messages> GF_Messages { get; set; }
        public DbSet<GF_MenuItems> GF_MenuItems { get; set; }
        public DbSet<GF_Settings> GF_Settings { get; set; }
        public DbSet<GF_OrderDetails> GF_OrderDetails { get; set; }
        public DbSet<GF_ContactList> GF_ContactList { get; set; }
        public DbSet<GF_CourseInfo> GF_CourseInfo { get; set; }
        public DbSet<GF_GolferUser> GF_GolferUser { get; set; }
        public DbSet<GF_GolferChangingLocation> GF_GolferChangingLocation { get; set; }
        public DbSet<GF_GolferWallet> GF_GolferWallet { get; set; }
        public DbSet<GF_PromoCode> GF_PromoCode { get; set; }
        public DbSet<GF_GolferRating> GF_GolferRating { get; set; }
        public DbSet<GF_ResolutionCenter> GF_ResolutionCenter { get; set; }
        public DbSet<GF_WeatherDetails> GF_WeatherDetails { get; set; }
        public DbSet<GF_UserCurrentPosition> GF_UserCurrentPosition { get; set; }
        public DbSet<GF_EmailTemplates> GF_EmailTemplates { get; set; }
        public DbSet<GF_EmailTemplatesFields> GF_EmailTemplatesFields { get; set; }
        public DbSet<GF_SMTPSettings> GF_SMTPSettings { get; set; }
        public DbSet<GF_StaticPages> GF_StaticPages { get; set; }
        public DbSet<GF_CourseFoodItem> GF_CourseFoodItem { get; set; }
        public DbSet<GF_CourseFoodItemDetail> GF_CourseFoodItemDetail { get; set; }
        public DbSet<GF_FoodCommission> GF_FoodCommission { get; set; }
        public DbSet<GF_CourseMenu> GF_CourseMenu { get; set; }
        public DbSet<GF_CourseVisitLog> GF_CourseVisitLog { get; set; }
        public DbSet<GF_GamePlayPlayerInfo> GF_GamePlayPlayerInfo { get; set; }
        public DbSet<GF_GamePlayScoreCard> GF_GamePlayScoreCard { get; set; }
        public DbSet<GF_CourseBuilder> GF_CourseBuilder { get; set; }
        public DbSet<GF_CourseBuilderHolesDetail> GF_CourseBuilderHolesDetail { get; set; }
        public DbSet<GF_CourseEmailTemplates> GF_CourseEmailTemplates { get; set; }
        public DbSet<GF_CourseBuilderRecDates> GF_CourseBuilderRecDates { get; set; }
        public DbSet<GF_GolferPaceofPlay> GF_GolferPaceofPlay { get; set; }
        public DbSet<GF_MenuItemOption> GF_MenuItemOption { get; set; }
        public DbSet<GF_ResolutionMessageHistory> GF_ResolutionMessageHistory { get; set; }
        public DbSet<GF_Order> GF_Order { get; set; }
        public DbSet<GF_OrderMenuOptionDetail> GF_OrderMenuOptionDetail { get; set; }
        public DbSet<GF_BlockUserList> GF_BlockUserList { get; set; }
        public DbSet<GF_CourseBlockUserList> GF_CourseBlockUserList { get; set; }
        public DbSet<GF_CourseMemberShip> GF_CourseMemberShip { get; set; }
        public DbSet<GF_GolferPaceofPlay_Temp> GF_GolferPaceofPlay_Temp { get; set; }
        public DbSet<GF_GamePlayRound> GF_GamePlayRound { get; set; }
        public DbSet<GF_Golfer> GF_Golfer { get; set; }
        public DbSet<GF_CourseFoodItemOption> GF_CourseFoodItemOption { get; set; }
        public DbSet<GF_Timezone> GF_Timezone { get; set; }
    
        public virtual ObjectResult<GF_SP_GetCourseLocation_Result> GF_SP_GetCourseLocation(string latitude, string longitude, Nullable<double> distance)
        {
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_GetCourseLocation_Result>("GF_SP_GetCourseLocation", latitudeParameter, longitudeParameter, distanceParameter);
        }
    
        public virtual ObjectResult<GF_SP_GetMessageListing_Result> GF_SP_GetMessageListing(Nullable<long> pgNo, Nullable<decimal> pgSize, Nullable<long> msgFrom, Nullable<long> msgTo, string isMessagesFromGolfer, string defaultImagePath, string golferImagePath, string courseImagePath)
        {
            var pgNoParameter = pgNo.HasValue ?
                new ObjectParameter("PgNo", pgNo) :
                new ObjectParameter("PgNo", typeof(long));
    
            var pgSizeParameter = pgSize.HasValue ?
                new ObjectParameter("PgSize", pgSize) :
                new ObjectParameter("PgSize", typeof(decimal));
    
            var msgFromParameter = msgFrom.HasValue ?
                new ObjectParameter("MsgFrom", msgFrom) :
                new ObjectParameter("MsgFrom", typeof(long));
    
            var msgToParameter = msgTo.HasValue ?
                new ObjectParameter("MsgTo", msgTo) :
                new ObjectParameter("MsgTo", typeof(long));
    
            var isMessagesFromGolferParameter = isMessagesFromGolfer != null ?
                new ObjectParameter("IsMessagesFromGolfer", isMessagesFromGolfer) :
                new ObjectParameter("IsMessagesFromGolfer", typeof(string));
    
            var defaultImagePathParameter = defaultImagePath != null ?
                new ObjectParameter("DefaultImagePath", defaultImagePath) :
                new ObjectParameter("DefaultImagePath", typeof(string));
    
            var golferImagePathParameter = golferImagePath != null ?
                new ObjectParameter("GolferImagePath", golferImagePath) :
                new ObjectParameter("GolferImagePath", typeof(string));
    
            var courseImagePathParameter = courseImagePath != null ?
                new ObjectParameter("CourseImagePath", courseImagePath) :
                new ObjectParameter("CourseImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_GetMessageListing_Result>("GF_SP_GetMessageListing", pgNoParameter, pgSizeParameter, msgFromParameter, msgToParameter, isMessagesFromGolferParameter, defaultImagePathParameter, golferImagePathParameter, courseImagePathParameter);
        }
    
        public virtual int GF_SP_GetCourseHoleDetail(Nullable<int> courseID)
        {
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GF_SP_GetCourseHoleDetail", courseIDParameter);
        }
    
        public virtual ObjectResult<GF_SP_GetFriendListing_Result> GF_SP_GetFriendListing(Nullable<long> pgNo, Nullable<decimal> pgSize, Nullable<long> userId, string friendType, Nullable<bool> isAllFriends, Nullable<long> courseId, string userType, string defaultImagePath, string golferImagePath, string courseImagePath)
        {
            var pgNoParameter = pgNo.HasValue ?
                new ObjectParameter("PgNo", pgNo) :
                new ObjectParameter("PgNo", typeof(long));
    
            var pgSizeParameter = pgSize.HasValue ?
                new ObjectParameter("PgSize", pgSize) :
                new ObjectParameter("PgSize", typeof(decimal));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var friendTypeParameter = friendType != null ?
                new ObjectParameter("FriendType", friendType) :
                new ObjectParameter("FriendType", typeof(string));
    
            var isAllFriendsParameter = isAllFriends.HasValue ?
                new ObjectParameter("IsAllFriends", isAllFriends) :
                new ObjectParameter("IsAllFriends", typeof(bool));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(long));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            var defaultImagePathParameter = defaultImagePath != null ?
                new ObjectParameter("DefaultImagePath", defaultImagePath) :
                new ObjectParameter("DefaultImagePath", typeof(string));
    
            var golferImagePathParameter = golferImagePath != null ?
                new ObjectParameter("GolferImagePath", golferImagePath) :
                new ObjectParameter("GolferImagePath", typeof(string));
    
            var courseImagePathParameter = courseImagePath != null ?
                new ObjectParameter("CourseImagePath", courseImagePath) :
                new ObjectParameter("CourseImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_GetFriendListing_Result>("GF_SP_GetFriendListing", pgNoParameter, pgSizeParameter, userIdParameter, friendTypeParameter, isAllFriendsParameter, courseIdParameter, userTypeParameter, defaultImagePathParameter, golferImagePathParameter, courseImagePathParameter);
        }
    
        public virtual ObjectResult<GF_SP_GetGolfersListingByCourseId_Result> GF_SP_GetGolfersListingByCourseId(Nullable<long> courseId)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_GetGolfersListingByCourseId_Result>("GF_SP_GetGolfersListingByCourseId", courseIdParameter);
        }
    
        public virtual ObjectResult<GF_SP_GetPersonWiseMessageListing_Result> GF_SP_GetPersonWiseMessageListing(Nullable<long> pgNo, Nullable<decimal> pgSize, Nullable<long> msgFrom, string isMessagesFromGolfer, string defaultImagePath, string golferImagePath, string courseImagePath)
        {
            var pgNoParameter = pgNo.HasValue ?
                new ObjectParameter("PgNo", pgNo) :
                new ObjectParameter("PgNo", typeof(long));
    
            var pgSizeParameter = pgSize.HasValue ?
                new ObjectParameter("PgSize", pgSize) :
                new ObjectParameter("PgSize", typeof(decimal));
    
            var msgFromParameter = msgFrom.HasValue ?
                new ObjectParameter("MsgFrom", msgFrom) :
                new ObjectParameter("MsgFrom", typeof(long));
    
            var isMessagesFromGolferParameter = isMessagesFromGolfer != null ?
                new ObjectParameter("IsMessagesFromGolfer", isMessagesFromGolfer) :
                new ObjectParameter("IsMessagesFromGolfer", typeof(string));
    
            var defaultImagePathParameter = defaultImagePath != null ?
                new ObjectParameter("DefaultImagePath", defaultImagePath) :
                new ObjectParameter("DefaultImagePath", typeof(string));
    
            var golferImagePathParameter = golferImagePath != null ?
                new ObjectParameter("GolferImagePath", golferImagePath) :
                new ObjectParameter("GolferImagePath", typeof(string));
    
            var courseImagePathParameter = courseImagePath != null ?
                new ObjectParameter("CourseImagePath", courseImagePath) :
                new ObjectParameter("CourseImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_GetPersonWiseMessageListing_Result>("GF_SP_GetPersonWiseMessageListing", pgNoParameter, pgSizeParameter, msgFromParameter, isMessagesFromGolferParameter, defaultImagePathParameter, golferImagePathParameter, courseImagePathParameter);
        }
    
        public virtual ObjectResult<GF_SP_SearchFriends_Result> GF_SP_SearchFriends(string searchStr, Nullable<long> courseId, string searchType, Nullable<long> userId, string userType, string defaultImagePath, string golferImagePath, string courseImagePath)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(long));
    
            var searchTypeParameter = searchType != null ?
                new ObjectParameter("SearchType", searchType) :
                new ObjectParameter("SearchType", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            var defaultImagePathParameter = defaultImagePath != null ?
                new ObjectParameter("DefaultImagePath", defaultImagePath) :
                new ObjectParameter("DefaultImagePath", typeof(string));
    
            var golferImagePathParameter = golferImagePath != null ?
                new ObjectParameter("GolferImagePath", golferImagePath) :
                new ObjectParameter("GolferImagePath", typeof(string));
    
            var courseImagePathParameter = courseImagePath != null ?
                new ObjectParameter("CourseImagePath", courseImagePath) :
                new ObjectParameter("CourseImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GF_SP_SearchFriends_Result>("GF_SP_SearchFriends", searchStrParameter, courseIdParameter, searchTypeParameter, userIdParameter, userTypeParameter, defaultImagePathParameter, golferImagePathParameter, courseImagePathParameter);
        }
    
        public virtual int GF_SP_BulkInsertGolflerLocation(string xMLData)
        {
            var xMLDataParameter = xMLData != null ?
                new ObjectParameter("XMLData", xMLData) :
                new ObjectParameter("XMLData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GF_SP_BulkInsertGolflerLocation", xMLDataParameter);
        }
    
        public virtual int GF_SP_BulkInsertPaceOfPlay(string xMLData)
        {
            var xMLDataParameter = xMLData != null ?
                new ObjectParameter("XMLData", xMLData) :
                new ObjectParameter("XMLData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GF_SP_BulkInsertPaceOfPlay", xMLDataParameter);
        }
    
        public virtual int GF_SP_deleteGolferChangingLocation_unused(Nullable<long> golferID)
        {
            var golferIDParameter = golferID.HasValue ?
                new ObjectParameter("GolferID", golferID) :
                new ObjectParameter("GolferID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GF_SP_deleteGolferChangingLocation_unused", golferIDParameter);
        }
    }
}
