//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_CourseFoodItemDetail
    {
        public GF_CourseFoodItemDetail()
        {
            this.GF_CourseFoodItemOption = new HashSet<GF_CourseFoodItemOption>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CourseFoodItemID { get; set; }
        public Nullable<long> MenuItemID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual GF_CourseFoodItem GF_CourseFoodItem { get; set; }
        public virtual GF_MenuItems GF_MenuItems { get; set; }
        public virtual ICollection<GF_CourseFoodItemOption> GF_CourseFoodItemOption { get; set; }
    }
}
