//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_GolferChangingLocation
    {
        public long Id { get; set; }
        public Nullable<long> GolferId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> TimeOfChange { get; set; }
        public string LocDetails { get; set; }
        public string LocType { get; set; }
        public Nullable<long> HoleNumber { get; set; }
    }
}
