//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_IncomeSlab
    {
        public GF_IncomeSlab()
        {
            this.GF_Golfer = new HashSet<GF_Golfer>();
        }
    
        public long ID { get; set; }
        public string Income { get; set; }
    
        public virtual ICollection<GF_Golfer> GF_Golfer { get; set; }
    }
}
