//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_OrderRefund
    {
        public long ID { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string Stripe_ChargeId { get; set; }
        public string Stripe_CustomerId { get; set; }
        public string RefundType { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string StripeMessage { get; set; }
        public string Description { get; set; }
    
        public virtual GF_Order GF_Order { get; set; }
    }
}
