//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_PromoCode
    {
        public GF_PromoCode()
        {
            this.GF_Order = new HashSet<GF_Order>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public string ReferenceType { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsOneTimeUse { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public string DiscountType { get; set; }
        public Nullable<long> OrderID { get; set; }
    
        public virtual GF_CourseInfo GF_CourseInfo { get; set; }
        public virtual ICollection<GF_Order> GF_Order { get; set; }
    }
}
