//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_SuggestCoordinateDetail
    {
        public long ID { get; set; }
        public Nullable<long> SuggestCoordinateID { get; set; }
        public Nullable<long> HoleNumber { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string DragItemType { get; set; }
        public string Discription { get; set; }
    
        public virtual GF_SuggestCourseCoordinate GF_SuggestCourseCoordinate { get; set; }
    }
}
